[build-system]
requires = ["meson-python>=0.16", "meson>=1.4", "ninja"]
build-backend = "mesonpy"

[project]
name = "wmf"
version = "1.3.0"
description = "Watershed Modelling Framework"
readme = "README.md"    # change to "README.txt" if that's what you have
requires-python = ">=3.8"
authors = [{ name = "Nicolas Velasquez G", email = "nicolas.velasquezgiron@gmail.com" }]
license = { text = "GPL-3.0-only" }
urls = { Homepage = "https://github.com/nicolas998/WMF" }